In [1]:
import pandas as pd
import numpy as np
import datetime

#%matplotlib inline

# Leo csv

In [2]:
avisos_detalle = pd.read_csv('../data/datos_navent_fiuba/fiuba_6_avisos_detalle.csv')
avisos_detalle = avisos_detalle.append(pd.read_csv('../data/fiuba_hasta_15_abril/fiuba_6_avisos_detalle.csv'))
avisos_detalle = avisos_detalle.append(pd.read_csv('../data/fiuba_desde_15_abril/fiuba_6_avisos_detalle.csv'))
avisos_detalle = avisos_detalle.append(pd.read_csv('../data/fiuba_6_avisos_detalle_missing_nivel_laboral.csv'))
avisos_detalle = avisos_detalle.reset_index().drop('index',axis=1)

In [3]:
avisos_detalle = avisos_detalle.drop(['ciudad','mapacalle','descripcion','titulo','denominacion_empresa','idpais'],axis=1)

In [4]:
postulantes_genero_y_edad = pd.read_csv('../data/datos_navent_fiuba/fiuba_2_postulantes_genero_y_edad.csv')
postulantes_genero_y_edad = postulantes_genero_y_edad.append(pd.read_csv('../data/fiuba_hasta_15_abril/fiuba_2_postulantes_genero_y_edad.csv'))
postulantes_genero_y_edad = postulantes_genero_y_edad.append(pd.read_csv('../data/fiuba_desde_15_abril/fiuba_2_postulantes_genero_y_edad.csv'))
postulantes_genero_y_edad = postulantes_genero_y_edad.reset_index().drop('index',axis=1)

In [5]:
postulaciones = pd.read_csv('../data/datos_navent_fiuba/fiuba_4_postulaciones.csv')
postulaciones = postulaciones.append(pd.read_csv('../data/fiuba_hasta_15_abril/fiuba_4_postulaciones.csv'))
# no tiene postulaciones -> pd.read_csv('data/fiuba_desde_15_abril/')
postulaciones = postulaciones.reset_index().drop('index',axis=1)

# Borro duplicados y agrego edad

In [6]:
postulantes_genero_y_edad = postulantes_genero_y_edad.drop_duplicates()
postulantes_genero_y_edad = postulantes_genero_y_edad.drop_duplicates(subset=['idpostulante'],keep='last')
postulantes_genero_y_edad = postulantes_genero_y_edad.reset_index().drop('index',axis=1)

In [7]:
# Agrego la edad de los postulantes
postulantes_genero_y_edad['fechanacimiento'] = pd.to_datetime(postulantes_genero_y_edad['fechanacimiento'],errors='coerce')
postulantes_genero_y_edad['edad'] = datetime.datetime.now().year - postulantes_genero_y_edad['fechanacimiento'].dt.year

# En un principio los relleno con la media de los postulantes
postulantes_genero_y_edad.loc[postulantes_genero_y_edad['edad'].isnull(),'edad'] = int(postulantes_genero_y_edad['edad'].mean())
postulantes_genero_y_edad['edad'] = postulantes_genero_y_edad['edad'].astype('int32')
postulantes_genero_y_edad.isnull().sum()

idpostulante           0
fechanacimiento    26096
sexo                   0
edad                   0
dtype: int64

In [8]:
avisos_detalle = avisos_detalle.drop_duplicates(subset=['idaviso'],keep='last')
avisos_detalle = avisos_detalle.reset_index().drop('index',axis=1)
avisos_detalle.isnull().sum()
avisos_detalle.loc[avisos_detalle['nivel_laboral'].isnull(),'nivel_laboral'] = 'Otro'
avisos_detalle.head()

,idaviso,nombre_zona,tipo_de_trabajo,nivel_laboral,nombre_area
0,1000872556,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Producción
1,9240880,Capital Federal,Full-time,Jefe / Supervisor / Responsable,Comercial
2,1110185164,Gran Buenos Aires,Full-time,Junior,Administración
3,1110513885,Gran Buenos Aires,Full-time,Junior,Distribución
4,1111034024,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Comercial

# Con esto dropeamos los avisos de postulaciones que no estan en detalles

In [9]:
postulaciones = postulaciones.drop_duplicates(keep='last')

In [ ]:
#estan=postulaciones['idaviso'].isin(avisos_detalle['idaviso'])
#estan.value_counts()

In [ ]:
#postulaciones = postulaciones[postulaciones['idaviso'].isin(avisos_detalle['idaviso'])]

In [ ]:
#postulaciones.shape

In [10]:
postulaciones = postulaciones.reset_index().drop('index',axis=1)

# Separo gente postulada y no postulada

In [12]:
# Separa la gente postulada, luego los busco en el DF que junta todos los postulantes
# y me quedo con los opuestos, los no postulados.
# esto me va a servir para samplear
# GENTE NO POSTULADA
gente_no_postulada = postulantes_genero_y_edad[-postulantes_genero_y_edad['idpostulante'].\
                                               isin(postulaciones['idpostulante'].value_counts().index)]
gente_no_postulada = gente_no_postulada.reset_index(drop=True)

In [13]:
# Pocos datos con sexo invalido, los desecho ya que son los no postulados
gente_no_postulada = gente_no_postulada.drop(gente_no_postulada[gente_no_postulada['sexo'] == '0.0'].index)

In [14]:
# GENTE POSTULADA
gente_postulada = postulantes_genero_y_edad[postulantes_genero_y_edad['idpostulante'].\
                                               isin(postulaciones['idpostulante'].value_counts().index)]
gente_postulada = gente_postulada.reset_index(drop=True)

In [15]:
# Reemplazo el sexo invalido por NO_DECLARA
gente_postulada.loc[gente_postulada['sexo'] == '0.0','sexo'] = 'NO_DECLARA'

In [16]:
# Dropeo los datos invalidos de los no postulados (se podria buscar alguna forma de salvarlos)
gente_no_postulada = gente_no_postulada.dropna()
gente_no_postulada = gente_no_postulada.reset_index(drop=True)
gente_no_postulada['edad'] = gente_no_postulada['edad'].astype('int32')

In [17]:
# En un principio los relleno con la media de los postulantes
gente_postulada.loc[gente_postulada['edad'].isnull(),'edad'] = int(postulantes_genero_y_edad['edad'].mean())
gente_postulada['edad'] = gente_postulada['edad'].astype('int32')

In [18]:
gente_postulada.isnull().sum()

idpostulante           0
fechanacimiento    10074
sexo                   0
edad                   0
dtype: int64

# Arreglo el df de avisos detalle

In [19]:
replacements = {
   'nombre_area': {
      'Ingeniería Geológica|Ingeniería Metalúrgica|Ingeniería  Metalurgica|Ingeniería  Eléctrica y Electrónica|Ingeniería  Automotriz|Ingeniería de Producto|Ingeniería de Procesos|Ingeniería de Ventas|Ingeniería Oficina Técnica / Proyecto|Ingeniería en Alimentos|Ingeniería Agrónoma|Ingeniería Química|Ingeniería  Industrial|Ingeniería Electromecánica|Ingeniería  Mecánica|Otras Ingenierias': 'Ingenieria',      
      'Corporate Finance / Banca Inversión|Evaluación Económica|Organización y Métodos|Cuentas Corrientes|Cadetería|Contabilidad|Impuestos|Auditoría|Control de Gestión|Consultoria': 'Administración',#cuentasc podria ir en ventas
      'Diseño Multimedia|Diseño 3D|Diseño Textil e Indumentaria|Diseño Web|Diseño de Interiores / Decoración|Diseño Industrial|Diseño Gráfico': 'Diseño y Urbanismo',
      'Periodismo|Comunicaciones Internas|Relaciones Institucionales/Publicas|Responsabilidad Social': 'Comunicacion',
      'Auditoría de Seguros|Venta de Seguros|Tecnico de Seguros|Administración de Seguros|Administracion de Seguros': 'Seguros',
      'Quimica|Bioquimica|Bioquímica': 'Química',
      'Selección|Capacitación|Compensación y Planilla|Administración de Personal': 'Recursos Humanos', #administracion de personal dudo
      'Exploración Minera y Petroquimica|Ingeniería en Petróleo y Petroquímica|Salud Minera|Seguridad Industrial|Medio Ambiente|Instrumentación Minera|Ingeniería en Minas|Mineria/Petroleo/Gas': 'Minería',
      'Traduccion': 'Idiomas',
      'Mantenimiento|Calidad|Programación de producción': 'Producción',
      'Inversiones / Proyectos de Inversión|Finanzas Internacionales|Análisis de Riesgos|Tesorería|Créditos y Cobranzas|Facturación|Planeamiento económico-financiero': 'Finanzas',
      'Telefonista|Call Center|Telemarketing|Caja': 'Atención al Cliente', #no se si caja va aca
      'Almacén / Depósito / Expedición|Compras|Distribución|Abastecimiento' : 'Logística',
      'Legal|Asesoría Legal Internacional': 'Legales',
      'Sistemas|Telecomunicaciones|Tecnologia/Sistemas de producción|Oficios Informática|Tecnologías de la Información|Data Warehousing|Redes|Data Entry|Administración de Base de Datos|Seguridad Informática|Soporte Técnico|Testing / QA / QC|Internet|Infraestructura|Análisis Funcional|Liderazgo de Proyecto|Programación' : 'Tecnologia/Sistemas',
      'Oficios y Profesiones|Producción y Limpieza|Estética y Cuidado Personal|Mantenimiento y Limpieza|Seguridad|Servicios|Promotoras/es|Jóvenes Profesionales': 'Oficios',#aca tambien
      'Recepcionista|Asistente': 'Secretaria',
      'Dirección de Obra|Arquitectura|Ingeniería Civil|Urbanismo|Operaciones|Diseño y Construcción|Topografía' : 'Construcción',
      'Compras Internacionales/Importación|Ventas Internacionales/Exportación|Consultorías Comercio Exterior|Apoderado Aduanal|Logística Internacionales/Importación': 'Comercio Exterior',
      'Business Intelligence|E-commerce|Community Management|Producto|Media Planning|Mercadotecnia Internacional': 'Marketing',
      'Camareros|Hotelería|Turismo': 'Gastronomia',
      'Seguridad Industrial|Oficios e Higiene' : 'Seguridad e Higiene',
      'Comercial|Ventas económico-financiero|Planeamiento Comercial|Planeamiento|Desarrollo de Negocios|Negocios Internacionales|Ventas comercial' : 'Ventas',
      'Laboratorio|Farmacia industrial|Farmacia comercial|Medicina|Otras Especialidades médicas|Diagnóstico por imágenes|Esterilización|Maternidad|Farmacéutica|Veterinaria|Odontología|Farmacia hospitalaria|Farmacia Industrial|Farmacia Comercial|Medicina Laboral|Instrumentación|Auditoría Médica|Emergentología|Kinesiología / terapia ocupacional|Prácticas cardiológicas|Otras áreas técnicas en salud|Fonoaudiología|Clínica Médica|Cuidados Intensivos Cardiologicos Adultos|Psicología|Instrumentación quirúrgica|Administración Médica' : 'Salud',
      'Gerencia / Dirección General|Dirección': 'Gerencia',
      'Pasantía / Trainee|Prácticas Profesionales': 'Pasantía',
      'Tecnologia / Tecnologia/Sistemas': 'Tecnologia/Sistemas',
      'Diseño y Construcción':'Construcción',
      'Secretaria de Tráfico': 'Logística',
      'Ventas comercial':'Ventas',
      'Salud Laboral|Salud quirúrgica':'Salud',
      'Educación/ Docentes|Educación especial|Trabajo social|Trabajo Social|Investigación y Desarrollo|Bienestar Estudiantil': 'Educación',
      'Arte y Cultura|Comunicaciones Externas|Independientes|Transporte|Creatividad|Multimedia|Back Office': 'Otros' #transporte entraria tanto en logistica como en oficios y creatividad en marketing y diseño
       #Multimedia en marketing y diseño. Back Office puede entrar en muchos
   }
}

avisos_detalle.replace(replacements, regex=True, inplace=True)

In [20]:
avisos_detalle.loc[avisos_detalle['nombre_area'] =='Enfermería (ver Enfermería)', "nombre_area"] = "Salud"

In [21]:
print(avisos_detalle['nombre_area'].value_counts())

Ventas                 5256
Administración         3218
Tecnologia/Sistemas    3062
Producción             2375
Atención al Cliente    1354
Logística              1332
Oficios                1180
Recursos Humanos       1012
Finanzas                929
Ingenieria              868
Salud                   727
Gastronomia             602
Construcción            585
Otros                   583
Marketing               579
Secretaria              459
Comercio Exterior       236
Legales                 235
Minería                 124
Seguros                 106
Gerencia                102
Comunicacion             92
Educación                86
Pasantía                 70
Seguridad e Higiene      49
Química                  40
Diseño                   22
Idiomas                   5
Name: nombre_area, dtype: int64

# Funciones

In [22]:
def oneHotEncoding(df, columna):
    one_hot = pd.get_dummies(df[columna])
    df.drop(columna, axis=1, inplace=True)
    df = pd.concat([df, one_hot], axis=1)
    return df

In [23]:
def feature_genero_edad(tupla_idaviso_idpostulante,postulantes_genero_y_edad):
    df_return = tupla_idaviso_idpostulante.merge(postulantes_genero_y_edad,on='idpostulante',how='left')
    return df_return

In [24]:
def feature_area_de_trabajo(tupla_a_predecir):
    df_return = tupla_a_predecir.merge(avisos_detalle,on='idaviso',how='left')
    return df_return

# Funciones utilidad

In [25]:
# Recibe las series de idpostulante e idaviso
def generador_de_sample_serie(idaviso, idpostulante, n_sample, ciclos):
    idpostulante = pd.DataFrame(idpostulante)
    idaviso = pd.DataFrame(idaviso)
    idpostulante['tem'] = 1
    idaviso['tem'] = 1
    sample_append = pd.DataFrame(columns=[idpostulante.columns[0],'tem',idaviso.columns[0]])
    for i in range(0,ciclos):
        sample_idpostulante = idpostulante.sample(n=n_sample,random_state=i)
        sample_idaviso = idaviso.sample(n=n_sample,random_state=i)
        sample_merge = sample_idaviso.merge(sample_idpostulante)
        sample_append = sample_append.append(sample_merge)
    sample_append = sample_append.drop('tem',axis=1)
    sample_append = sample_append.reset_index(drop=True)
    return sample_append

In [26]:
# fijarse de balancear el sample con 50% de postulados y no postulados

# Generador de sample
# el id tiene que estar en la columna 0
# Recibe los DFs de idpostulante e idaviso
def generador_de_sample_df(idaviso, idpostulante, n_sample, ciclos):
    idpostulante = idpostulante.drop(columns=idpostulante.columns[1:])
    idaviso = idaviso.drop(columns=idaviso.columns[1:])
    idpostulante['tem'] = 1
    idaviso['tem'] = 1
    sample_append = pd.DataFrame(columns=[idpostulante.columns[0],'tem',idaviso.columns[0]])
    for i in range(0,ciclos):
        sample_idpostulante = idpostulante.sample(n=n_sample,random_state=i)
        sample_idaviso = idaviso.sample(n=n_sample,random_state=i)
        sample_merge = sample_idaviso.merge(sample_idpostulante)
        sample_append = sample_append.append(sample_merge)
    sample_append = sample_append.drop('tem',axis=1)
    sample_append = sample_append.reset_index(drop=True)
    return sample_append

# Tupla postulada y sample no postulado

In [27]:
tupla_postulada = postulaciones.drop('fechapostulacion',axis=1)
tupla_postulada['y'] = 1
tupla_postulada = feature_genero_edad(tupla_postulada,gente_postulada)
tupla_postulada = tupla_postulada.drop(['fechanacimiento'],axis=1)
tupla_postulada = oneHotEncoding(tupla_postulada,'sexo')

In [28]:
tupla_postulada.head()

      idaviso idpostulante  y  edad  FEM  MASC  NO_DECLARA
0  1112257047         NM5M  1    48    1     0           0
1  1111920714         NM5M  1    48    1     0           0
2  1112346945         NM5M  1    48    1     0           0
3  1112345547         NM5M  1    48    1     0           0
4  1112237522         5awk  1    56    1     0           0

In [29]:
sample = generador_de_sample_serie(avisos_detalle['idaviso'],gente_no_postulada['idpostulante'],10,1000)
sample['y'] = 0
sample = feature_genero_edad(sample,gente_no_postulada)
sample = sample.drop(['fechanacimiento'],axis=1)
sample = oneHotEncoding(sample,'sexo')

In [30]:
sample.head()

      idaviso idpostulante  y  edad  FEM  MASC  NO_DECLARA
0  1112390041      GNZ8JWK  0    55    0     1           0
1  1112390041      ZDlz5E1  0    21    1     0           0
2  1112390041        a0N4q  0    43    1     0           0
3  1112390041       ep41j9  0    32    0     1           0
4  1112390041       awOL1m  0    34    1     0           0

# Borro lo que no necesito

In [31]:
#del avisos_detalle
del postulantes_genero_y_edad
del postulaciones

# Separo la edad por rango en el sample y el test

In [32]:
sample = sample.append(tupla_postulada.sample(n=100000,random_state=0))

In [33]:
sample = sample.drop('idpostulante',axis=1)

In [34]:
sample['edad'] = pd.cut(sample['edad'], range(0, 100, 5))
sample['edad'] = sample['edad'].astype(str)
dic = {'(10, 15]':0 , '(15, 20]':1 , '(20, 25]':2 , '(25, 30]':3 , '(30, 35]':4 , '(35, 40]':5 , '(40, 45]':6 , '(45, 50]':7 , '(50, 55]':8 , '(55, 60]':9 , '(60, 65]':10 , '(65, 70]':11 , '(70, 75]':12 , '(75, 80]':13 , '(80, 85]':14 , '(85, 90]':15 , '(95, 100]':16 , '(240, 245]':17}
sample['edad'] = sample['edad'].map(dic)

In [35]:
sample['edad'] = sample['edad'].fillna(2)

In [36]:
sample = feature_area_de_trabajo(sample)

In [37]:
sample.isnull().sum()

idaviso               0
y                     0
edad                  0
FEM                   0
MASC                  0
NO_DECLARA            0
nombre_zona        6214
tipo_de_trabajo    6214
nivel_laboral      6214
nombre_area        6214
dtype: int64

## Y aca dropeamos despues

In [38]:
sample.dropna()

,idaviso,y,edad,FEM,MASC,NO_DECLARA,nombre_zona,tipo_de_trabajo,nivel_laboral,nombre_area
0,1112390041,0,8.0,0,1,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Oficios
1,1112390041,0,2.0,1,0,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Oficios
2,1112390041,0,6.0,1,0,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Oficios
3,1112390041,0,4.0,0,1,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Oficios
4,1112390041,0,4.0,1,0,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Oficios
5,1112390041,0,6.0,1,0,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Oficios
6,1112390041,0,7.0,0,1,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Oficios
7,1112390041,0,9.0,0,1,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Oficios
8,1112390041,0,5.0,0,1,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Oficios
9,1112390041,0,1.0,0,1,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Oficios
10,1112246523,0,8.0,0,1,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Tecnologia/Sistemas
11,1112246523,0,2.0,1,0,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Tecnologia/Sistemas
12,1112246523,0,6.0,1,0,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Tecnologia/Sistemas
13,1112246523,0,4.0,0,1,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Tecnologia/Sistemas
14,1112246523,0,4.0,1,0,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Tecnologia/Sistemas
15,1112246523,0,6.0,1,0,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Tecnologia/Sistemas
16,1112246523,0,7.0,0,1,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Tecnologia/Sistemas
17,1112246523,0,9.0,0,1,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Tecnologia/Sistemas
18,1112246523,0,5.0,0,1,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Tecnologia/Sistemas
19,1112246523,0,1.0,0,1,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Tecnologia/Sistemas
20,1112424481,0,8.0,0,1,0,Gran Buenos Aires,Full-time,Junior,Gastronomia
21,1112424481,0,2.0,1,0,0,Gran Buenos Aires,Full-time,Junior,Gastronomia
22,1112424481,0,6.0,1,0,0,Gran Buenos Aires,Full-time,Junior,Gastronomia
23,1112424481,0,4.0,0,1,0,Gran Buenos Aires,Full-time,Junior,Gastronomia
24,1112424481,0,4.0,1,0,0,Gran Buenos Aires,Full-time,Junior,Gastronomia
25,1112424481,0,6.0,1,0,0,Gran Buenos Aires,Full-time,Junior,Gastronomia
26,1112424481,0,7.0,0,1,0,Gran Buenos Aires,Full-time,Junior,Gastronomia
27,1112424481,0,9.0,0,1,0,Gran Buenos Aires,Full-time,Junior,Gastronomia
28,1112424481,0,5.0,0,1,0,Gran Buenos Aires,Full-time,Junior,Gastronomia
29,1112424481,0,1.0,0,1,0,Gran Buenos Aires,Full-time,Junior,Gastronomia
...,...,...,...,...,...,...,...,...,...,...
199966,1112326501,1,2.0,1,0,0,Gran Buenos Aires,Full-time,Junior,Administración
199968,1112316794,1,3.0,0,1,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Ventas
199969,1112391179,1,3.0,1,0,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Administración
199970,1112247217,1,2.0,1,0,0,Gran Buenos Aires,Part-time,Junior,Atención al Cliente
199971,1112213212,1,5.0,1,0,0,Capital Federal,Full-time,Otro,Seguros
199972,1112418587,1,2.0,1,0,0,Gran Buenos Aires,Part-time,Junior,Atención al Cliente
199973,1112276943,1,3.0,1,0,0,Gran Buenos Aires,Full-time,Otro,Producción
199974,1112261096,1,3.0,1,0,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Construcción
199975,1112460858,1,4.0,0,1,0,Gran Buenos Aires,Part-time,Senior / Semi-Senior,Atención al Cliente
199976,1112423634,1,2.0,0,1,0,Gran Buenos Aires,Part-time,Senior / Semi-Senior,Atención al Cliente
199977,1112351894,1,6.0,0,1,0,Gran Buenos Aires,Full-time,Gerencia / Alta Gerencia / Dirección,Gerencia
199978,1112377249,1,7.0,1,0,0,Gran Buenos Aires,Full-time,Otro,Secretaria
199979,1112345893,1,2.0,1,0,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Secretaria
199981,1112448200,1,4.0,0,1,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Oficios
199982,1112225883,1,4.0,1,0,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Construcción
199983,1112094756,1,5.0,1,0,0,Gran Buenos Aires,Part-time,Senior / Semi-Senior,Atención al Cliente
199984,1112261322,1,2.0,1,0,0,Gran Buenos Aires,Fines de Semana,Senior / Semi-Senior,Ventas
199986,1112374555,1,2.0,0,1,0,Gran Buenos Aires,Full-time,Junior,Administración
199987,1112349911,1,4.0,0,0,1,Gran Buenos Aires,Full-time,Junior,Comercio Exterior
199988,1112446807,1,4.0,1,0,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Administración
199989,1112355615,1,2.0,1,0,0,Gran Buenos Aires,Full-time,Junior,Finanzas
199991,1112119698,1,5.0,1,0,0,Gran Buenos Aires,Full-time,Otro,Salud
199992,1111970596,1,2.0,0,1,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Atención al Cliente
199993,1112381043,1,5.0,1,0,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Secretaria
199994,1112339031,1,9.0,0,1,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Producción
199995,1112365014,1,5.0,1,0,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Atención al Cliente
199996,1112312230,1,1.0,0,1,0,Gran Buenos Aires,Full-time,Junior,Atención al Cliente
199997,1112309579,1,2.0,1,0,0,Gran Buenos Aires,Part-time,Senior / Semi-Senior,Atención al Cliente
199998,1112383525,1,2.0,0,1,0,Gran Buenos Aires,Full-time,Senior / Semi-Senior,Atención al Cliente
199999,1112352366,1,2.0,1,0,0,Gran Buenos Aires,Pasantia,Junior,Marketing

In [39]:
sample = oneHotEncoding(sample,'nombre_area')

In [40]:
sample = oneHotEncoding(sample,'nivel_laboral')

In [41]:
sample = oneHotEncoding(sample,'nombre_zona')

In [42]:
sample = oneHotEncoding(sample,'tipo_de_trabajo')

In [43]:
sample = sample.drop(['idaviso'],axis=1)

In [44]:
sample.head()

,y,edad,FEM,MASC,NO_DECLARA,Administración,Atención al Cliente,Comercio Exterior,Comunicacion,Construcción,...,Fines de Semana,Full-time,Part-time,Pasantia,Por Contrato,Por Horas,Primer empleo,Teletrabajo,Temporario,Voluntario
0,0,8.0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,0,2.0,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,0,6.0,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,0,4.0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,0,4.0,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [51]:
sample['y'].value_counts()

1    100000
0    100000
Name: y, dtype: int64

# Random Forest

In [45]:
#-----------------------------------------------------------------
# Modelo Random Forest Classifier
#-----------------------------------------------------------------
from sklearn.ensemble import RandomForestClassifier

In [46]:
# Divido el set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(sample.drop(columns='y'),sample['y'],random_state=0,test_size=0.01)

In [47]:
ModeloRFC = RandomForestClassifier(n_estimators=100,random_state=0, n_jobs=-1)

In [48]:
#ModeloRFC.fit(train_data, train_label)
ModeloRFC.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [49]:
#result = ModeloRFC.predict(test_final)
result = ModeloRFC.predict(X_test)

In [50]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,result)
#0.6538586168926441 con genero+edad+nombre area
#0.6425822524525469 con genero+edad+nombre area(un poco mas reducidas-no sirvio)
#0.6570570038974716 con genero+edad+nombre area+nivel laboral
#0.668541893569122  con genero+edad+nombre area+nivel laboral+tipo trabajo+ nombre zona
#0.668541893569122  con genero+edad+nombre area+nivel laboral+tipo trabajo+ nombre zona dropeando despues
#0.6553753004113497 con genero+edad+nombre area+nivel laboral+tipo trabajo+ nombre zona sacando los avisos que no tienen detalles al ppio

0.668541893569122